### ISSUE TITLE
Update Node12 -> Node16

### ISSUE THREAD

**Issue by henningWoehr** [ctrlaltdev/get-releases-action#6]
Hello,
Node12 has recently become deprecated. It's not urgent, but it would be nice, if this action could be updated, so that I can keep using it and the warning with every workflow run disappears.

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by ctrlaltdev** [comment]
Hey @henningWoehr

Thank you for bringing this to my attention :)
v1.2.0 is out and running on node 16!
